export const skills = [
    "HTML",
    "CSS",
    "JavaScript",
    "Java",
    "Python",
    "C++",
    "C#",
    "PHP",
    "Ruby",
    "Swift",
    "TypeScript",
    "Node.js",
    "React",
    "Angular",
    "Vue.js",
    "Express.js",
    "Django",
    "Flask",
    "Spring Framework",
    "Bootstrap",
    "Sass",
    "Less",
    "jQuery",
    "RESTful API",
    "GraphQL",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "JIRA",
    "Agile Development",
    "Scrum",
    "Kanban",
    "Continuous Integration",
    "Continuous Deployment",
    "DevOps",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Ansible",
    "Chef",
    "Puppet",
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "Firebase",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "NoSQL",
    "Firebase",
    "Firebase Firestore",
    "Firebase Realtime Database",
    "Elasticsearch",
    "Blockchain",
    "Smart Contracts",
    "Solidity",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Data Science",
    "Big Data",
    "Hadoop",
    "Spark",
    "Apache Kafka",
    "RESTful API Design",
    "Microservices Architecture",
    "GraphQL",
    "WebSocket",
    "OAuth",
    "JWT (JSON Web Tokens)",
    "OAuth 2.0",
    "JSON",
    "XML",
    "WebSockets",
    "Responsive Web Design",
    "Cross-browser Compatibility",
    "UI/UX Design",
    "Adobe Creative Suite",
    "Figma",
    "Sketch",
    "Zeplin",
    "Microsoft Office",
    "Project Management",
    "Leadership",
    "Communication",
    "Problem Solving",
    "Critical Thinking",
    "Agile Methodologies",
    "Team Collaboration",
    "Version Control",
    "Unit Testing",
    "Integration Testing",
    "Automation Testing",
    "Containerization",
    "Infrastructure as Code (IaC)",
    "Security Best Practices",
];
